/**
389. Find the Difference


Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.

 */


/**
 * @param {string} s
 * @param {string} t
 * @return {character}
 */
var findTheDifference = function(s, t) {
    const cache = {};
    for ( let i = 0 ; i < t.length ; i++ ) {
        cache[s[i]] = cache[s[i]] || 0;
        cache[s[i]]++;
    }
    for ( let i = 0 ; i < t.length ; i++ ) {
        if ( cache[t[i]] ) {
            cache[ t[i] ]--;
        } else {
            return t[i];
        }
    }
    
    return null;
    
};


/** 
"abcd"
"abfcd"
"abcd"
"abbcd"
"a"
"ab"
""
"a"
*/